### ISSUE TITLE
feature request: dependency management

### ISSUE THREAD

**Issue by matthewhartstonge** [aciddude/capi#5]
Heyo!

Just wondering if you are thinking about adding dependency management?

Would be helpful to ensure builds don't break if a dependency changes it's API. 😄 
This enables quick hacking for developers by running `go get` ([go mod](https://github.com/golang/go/wiki/Modules)) or `dep ensure` ([dep](https://github.com/golang/dep)) to pull down all dependencies in one hit.

**Comment by aciddude** [comment]
I would have to take someones lead on that as i havent done that in go lang yet

**Comment by matthewhartstonge** [comment]
Cool, I'll investigate `go mod` (new to me as well) as the community appears to be converging on that and will be the default come Go 1.13 (2019 August 1st), initially released with Go 1.11.
From initial investigation, this may mean having to set a local environment variable as we need to tell Go to use go modules if developing in `GOPATH`.

**Comment by aciddude** [comment]
Merged!
